/** Font family used across all editor UI */
export const EDITOR_FONT_FAMILY = "'Montserrat', -apple-system, BlinkMacSystemFont, sans-serif";

/**
 * Editor styles - shared style objects for editor UI (no Tailwind)
 */
export const editorStyles = {
  root: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1.5rem',
    maxWidth: '100%',
    minHeight: '100%',
    fontFamily: EDITOR_FONT_FAMILY,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '1rem',
    borderBottom: '1px solid rgba(226,232,240,0.8)',
  },
  headerTitle: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: '#1e293b',
    letterSpacing: '-0.025em',
    fontFamily: EDITOR_FONT_FAMILY,
  },
  closeBtn: {
    width: '2.25rem',
    height: '2.25rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '0.75rem',
    color: '#94a3b8',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '3rem 1.5rem',
    background: 'linear-gradient(to bottom right, #f8fafc, rgba(239,246,255,0.5))',
    border: '2px dashed #e2e8f0',
    borderRadius: '1rem',
  },
  emptyStateIcon: {
    width: '4rem',
    height: '4rem',
    margin: '0 auto 1rem',
    borderRadius: '1rem',
    background: 'linear-gradient(to bottom right, #dbeafe, #bfdbfe)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateText: {
    color: '#475569',
    fontSize: '0.875rem',
    marginBottom: '1.25rem',
    lineHeight: 1.625,
  },
  primaryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.75rem 1.5rem',
    borderRadius: '0.75rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#fff',
    background: 'linear-gradient(to right, #3b82f6, #2563eb)',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  secondaryBtn: {
    flex: 1,
    padding: '0.75rem 1.25rem',
    borderRadius: '0.75rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    background: '#f1f5f9',
    color: '#334155',
    border: '1px solid #e2e8f0',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  section: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
  },
  label: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#475569',
    fontFamily: EDITOR_FONT_FAMILY,
  },
  selectorBox: {
    padding: '0.625rem 1rem',
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    fontFamily: 'ui-monospace, monospace',
    fontSize: '0.75rem',
    color: '#334155',
    wordBreak: 'break-all' as const,
  },
  elementInfo: {
    padding: '1rem',
    background: 'rgba(239,246,255,0.9)',
    border: '1px solid #bfdbfe',
    borderRadius: '0.75rem',
  },
  elementInfoTitle: {
    display: 'block',
    marginBottom: '0.5rem',
    fontSize: '0.75rem',
    fontWeight: 700,
    color: '#1d4ed8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  elementInfoText: {
    fontSize: '0.875rem',
    color: 'rgba(29,78,216,0.9)',
  },
  textarea: {
    width: '100%',
    padding: '0.75rem 1rem',
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    fontSize: '0.875rem',
    color: '#0f172a',
    background: '#fff',
    minHeight: '100px',
    lineHeight: 1.625,
    resize: 'vertical' as const,
    fontFamily: EDITOR_FONT_FAMILY,
  },
  input: {
    width: '100%',
    padding: '0.75rem 1rem',
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    fontSize: '0.875rem',
    color: '#0f172a',
    background: '#fff',
    fontFamily: EDITOR_FONT_FAMILY,
  },
  placementGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '0.5rem',
  },
  placementBtn: (active: boolean) => ({
    padding: '0.75rem 1rem',
    borderRadius: '0.75rem',
    fontSize: '0.875rem',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
    ...(active
      ? { background: '#3b82f6', color: '#fff', border: 'none' }
      : { background: '#fff', color: '#475569', border: '1px solid #e2e8f0' }),
  }),
  errorBox: {
    padding: '0.75rem 1rem',
    background: '#fef2f2',
    border: '1px solid #fee2e2',
    borderRadius: '0.75rem',
    color: '#b91c1c',
    fontSize: '0.875rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  actionRow: {
    display: 'flex',
    gap: '0.75rem',
    paddingTop: '1rem',
    marginTop: '0.5rem',
    borderTop: '1px solid rgba(226,232,240,0.8)',
  },
  panel: {
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: '100%',
    background: '#fff',
  },
  panelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 1.5rem',
    borderBottom: '1px solid rgba(226,232,240,0.8)',
    background: 'rgba(248,250,252,0.5)',
  },
  panelBody: {
    flex: 1,
    padding: '1.5rem',
    overflowY: 'auto' as const,
  },
  iconBtn: {
    width: '2.25rem',
    height: '2.25rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '0.75rem',
    color: '#94a3b8',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  card: {
    background: '#fff',
    borderRadius: '1rem',
    padding: '1.25rem',
    border: '1px solid rgba(226,232,240,0.8)',
    transition: 'all 0.2s',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    fontSize: '0.75rem',
    fontWeight: 700,
    padding: '0.125rem 0.625rem',
    flexShrink: 0,
  },
  sectionLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#94a3b8',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.1em',
    marginBottom: '0.75rem',
  },
  tabRow: {
    display: 'flex',
    gap: 0,
    borderBottom: '1px solid rgba(226,232,240,0.8)',
    padding: '0 1.5rem',
    background: '#fff',
  },
  tab: (active: boolean) => ({
    padding: '1rem 1.25rem',
    fontSize: '0.875rem',
    fontWeight: active ? 600 : 500,
    color: active ? '#2563eb' : '#64748b',
    cursor: 'pointer',
    position: 'relative' as const,
    background: 'none',
    border: 'none',
    fontFamily: EDITOR_FONT_FAMILY,
    borderBottom: active ? '2px solid #3b82f6' : '2px solid transparent',
  }),
  heatmapRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1.25rem 0',
    borderTop: '1px solid rgba(226,232,240,0.8)',
    marginTop: '1.5rem',
  },
  toggle: (on: boolean) => ({
    position: 'relative' as const,
    width: '3rem',
    height: '1.75rem',
    borderRadius: '9999px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    background: on ? '#10b981' : '#cbd5e1',
    border: 'none',
  }),
  toggleThumb: (on: boolean) => ({
    position: 'absolute' as const,
    top: '0.25rem',
    left: on ? '1.5rem' : '0.25rem',
    width: '1.25rem',
    height: '1.25rem',
    background: '#fff',
    borderRadius: '9999px',
    transition: 'all 0.2s',
  }),
  link: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.375rem',
    color: '#2563eb',
    fontSize: '0.875rem',
    fontWeight: 500,
    textDecoration: 'none',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    fontFamily: EDITOR_FONT_FAMILY,
  },
  footer: {
    display: 'flex',
    gap: '0.75rem',
    padding: '1rem 1.5rem',
    borderTop: '1px solid rgba(226,232,240,0.8)',
    background: 'rgba(248,250,252,0.5)',
    marginTop: 'auto',
  },
  radioLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    cursor: 'pointer',
    padding: '0.75rem',
    borderRadius: '0.75rem',
    border: '1px solid #e2e8f0',
    transition: 'all 0.2s',
  },
  searchWrap: {
    position: 'relative' as const,
    marginBottom: '1rem',
  },
  searchIcon: {
    position: 'absolute' as const,
    left: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94a3b8',
    fontSize: '1rem',
  },
  searchInput: {
    width: '100%',
    padding: '0.75rem 1rem 0.75rem 2.75rem',
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    fontSize: '0.875rem',
    color: '#0f172a',
    background: '#fff',
    fontFamily: EDITOR_FONT_FAMILY,
  },
  pageItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1.25rem',
    background: '#fff',
    borderRadius: '1rem',
    border: '1px solid rgba(226,232,240,0.8)',
    marginBottom: '0.5rem',
    transition: 'all 0.2s',
  },
  iconBtnSm: {
    width: '2rem',
    height: '2rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '0.5rem',
    color: '#94a3b8',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  comingSoon: {
    padding: '2rem 0',
    textAlign: 'center' as const,
  },
  comingSoonIcon: {
    width: '4rem',
    height: '4rem',
    margin: '0 auto 1rem',
    borderRadius: '1rem',
    background: '#f1f5f9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
} as const;

/** Minimal CSS string for iframe injection (iconify + base + font) */
export const editorStylesCss = `
* { font-family: ${EDITOR_FONT_FAMILY}; }
iconify-icon { display: inline-block; width: 1em; height: 1em; vertical-align: -0.125em; }
@keyframes editor-spin { to { transform: rotate(360deg); } }
.editor-spinner { display: inline-block; animation: editor-spin 0.8s linear infinite; }
`;
